# Generated by Django 5.2.1 on 2025-05-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dateForm', models.DateField()),
                ('hour', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('freeState', models.BooleanField(default=False)),
                ('outstanding', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
